[[language]]
name = "json"
language-servers = ["biome"]

[[language]]
name = "markdown"
auto-format = true
language-servers = ["marksman", "rumdl", "mpls"]
formatter = { command = "rumdl", args = ["check", "--fix", "--stdin"] }

[[language]]
name = "pkl"
auto-format = true

[language-server.biome]
command = "biome"
args = ["lsp-proxy"]

[language-server.mpls]
command = "mpls"
args = ["--theme", "dark", "--enable-emoji", "--full-sync"]

[language-server.rumdl]
command = "rumdl"
args = ["server"]

[language-server.rust-analyzer.config]
check.command = "clippy"
imports.granularity.enforce = true
imports.granularity.group = "module"
